package com.drivingschool.common.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

/**
 * Centralized stable {@code errorCode} strings for API clients and their typical HTTP status.
 * Domain rules use {@link BusinessException} with these values; the global handler also uses
 * the framework entries ({@link #RESOURCE_NOT_FOUND}, validation, etc.) for consistent responses.
 */
@Getter
public enum ErrorCode {

    // Framework / cross-cutting (not thrown as BusinessException)
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND", HttpStatus.NOT_FOUND),
    VALIDATION_FAILED("VALIDATION_FAILED", HttpStatus.BAD_REQUEST),
    CONSTRAINT_VIOLATION("CONSTRAINT_VIOLATION", HttpStatus.BAD_REQUEST),
    UNAUTHORIZED("UNAUTHORIZED", HttpStatus.UNAUTHORIZED),
    FORBIDDEN("FORBIDDEN", HttpStatus.FORBIDDEN),
    INTERNAL_ERROR("INTERNAL_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),

    // Duplicate / uniqueness
    DUPLICATE_LICENSE_PLATE("DUPLICATE_LICENSE_PLATE", HttpStatus.BAD_REQUEST),
    DUPLICATE_LICENSE_NUMBER("DUPLICATE_LICENSE_NUMBER", HttpStatus.BAD_REQUEST),
    DUPLICATE_EMAIL("DUPLICATE_EMAIL", HttpStatus.BAD_REQUEST),
    DUPLICATE_CNP("DUPLICATE_CNP", HttpStatus.BAD_REQUEST),
    DUPLICATE_TRANSACTION("DUPLICATE_TRANSACTION", HttpStatus.BAD_REQUEST),

    // Vehicle
    VEHICLE_ALREADY_IN_MAINTENANCE("VEHICLE_ALREADY_IN_MAINTENANCE", HttpStatus.BAD_REQUEST),
    VEHICLE_NOT_IN_MAINTENANCE("VEHICLE_NOT_IN_MAINTENANCE", HttpStatus.BAD_REQUEST),
    VEHICLE_NOT_AVAILABLE("VEHICLE_NOT_AVAILABLE", HttpStatus.BAD_REQUEST),
    VEHICLE_INSURANCE_EXPIRED("VEHICLE_INSURANCE_EXPIRED", HttpStatus.BAD_REQUEST),
    VEHICLE_HAS_SCHEDULING("VEHICLE_HAS_SCHEDULING", HttpStatus.CONFLICT),

    // Student
    STUDENT_NOT_ACTIVE("STUDENT_NOT_ACTIVE", HttpStatus.BAD_REQUEST),
    INVALID_DRIVING_CATEGORY("INVALID_DRIVING_CATEGORY", HttpStatus.BAD_REQUEST),
    TARGET_LICENSE_CATEGORIES_REQUIRED("TARGET_LICENSE_CATEGORIES_REQUIRED", HttpStatus.BAD_REQUEST),
    DOCUMENT_UPDATE_EMPTY("DOCUMENT_UPDATE_EMPTY", HttpStatus.BAD_REQUEST),
    DOCUMENT_FILE_PATH_INVALID("DOCUMENT_FILE_PATH_INVALID", HttpStatus.BAD_REQUEST),

    // Instructor / cross-service
    INSTRUCTOR_HAS_SCHEDULING("INSTRUCTOR_HAS_SCHEDULING", HttpStatus.CONFLICT),
    SCHEDULING_DEPENDENCY_CHECK_FAILED("SCHEDULING_DEPENDENCY_CHECK_FAILED", HttpStatus.SERVICE_UNAVAILABLE),

    // Scheduling
    INVALID_COURSE_TAG("INVALID_COURSE_TAG", HttpStatus.BAD_REQUEST),
    INVALID_TIME("INVALID_TIME", HttpStatus.BAD_REQUEST),
    INVALID_TIME_RANGE("INVALID_TIME_RANGE", HttpStatus.BAD_REQUEST),
    SCHEDULING_CONFLICT("SCHEDULING_CONFLICT", HttpStatus.BAD_REQUEST),
    LESSON_WITHOUT_COURSE("LESSON_WITHOUT_COURSE", HttpStatus.BAD_REQUEST),
    MISSING_COURSE_ID("MISSING_COURSE_ID", HttpStatus.BAD_REQUEST),
    COURSE_HAS_LESSONS("COURSE_HAS_LESSONS", HttpStatus.BAD_REQUEST),

    // Payment
    INVALID_REFUND_STATUS("INVALID_REFUND_STATUS", HttpStatus.BAD_REQUEST),
    INVALID_STATUS_CHANGE("INVALID_STATUS_CHANGE", HttpStatus.BAD_REQUEST),
    MISSING_LESSON_ID("MISSING_LESSON_ID", HttpStatus.BAD_REQUEST),
    NO_PENDING_PAYMENT("NO_PENDING_PAYMENT", HttpStatus.BAD_REQUEST),
    MISSING_PAYMENT_METHOD("MISSING_PAYMENT_METHOD", HttpStatus.BAD_REQUEST),
    PAYMENT_DELETE_NOT_ALLOWED("PAYMENT_DELETE_NOT_ALLOWED", HttpStatus.CONFLICT),

    BUSINESS_ERROR("BUSINESS_ERROR", HttpStatus.BAD_REQUEST);

    private final String code;
    private final HttpStatus httpStatus;

    ErrorCode(String code, HttpStatus httpStatus) {
        this.code = code;
        this.httpStatus = httpStatus;
    }

    @Override
    public String toString() {
        return code;
    }
}
