apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namespace: dsms-azure

# Deploying directly using GHCR images instead of ACR.
# If you ever want to revert to ACR, you can define image overrides here.
