apiVersion: v1
kind: Secret
metadata:
  name: dsms-secrets
  namespace: default
type: Opaque
stringData:
  jwt-secret: "replace-this-with-a-long-secret-key-for-local-dev-1234567890"
  postgres-user: "postgres"
  postgres-password: "postgres"
  mongodb-uri: "mongodb://mongodb:27017/drivingschool-notifications"